# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Hwaro < Formula
  desc "() is a lightweight and fast static site generator written in crystal"
  homepage "https://github.com/hahwul/hwaro"
  url "https://github.com/hahwul/hwaro/archive/refs/tags/v0.0.5_1.tar.gz"
  sha256 "70501ccf6d3ff0f51d89947737436bec98beb58aed0e08217c17235f20d59d94"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/hwaro"
  end

  test do
    system "{bin}/hwaro", "version"
  end
end
