# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Hwaro < Formula
  desc "() is a lightweight and fast static site generator written in crystal"
  homepage "https://github.com/hahwul/hwaro"
  url "https://github.com/hahwul/hwaro/archive/refs/tags/v0.0.1.tar.gz"
  sha256 "9a51dc09cbc8b78bb7e2a5c6fbb5a7ce714f35ee35983c922f8578baf80f9580"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/hwaro"
  end

  test do
    system "{bin}/hwaro", "version"
  end
end
