# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Hwaro < Formula
  desc "() is a lightweight and fast static site generator(ssg) written in cryst"
  homepage "https://github.com/hahwul/hwaro"
  url "https://github.com/hahwul/hwaro/archive/refs/tags/v0.9.1.tar.gz"
  sha256 "6b18b16218491dddbf4230da75f78df9ece73ae3dda410582b0cebdd807b49e3"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/hwaro"
  end

  test do
    system "{bin}/hwaro", "version"
  end
end
